rules:
  unpinned-uses:
    config:
      policies: # Allow unpinned references to starflow.
        canonical/starflow/*: ref-pin
  excessive-permissions:
    ignore:
      # test-python.yaml needs actions:read, blocked on downstream coordination.
      # https://github.com/canonical/starflow/issues/174
      - .github/workflows/test-python.yaml
