name: Code Analysis

on:
  workflow_call:
    inputs:
      platform-tags:
        type: string
        default: '"jammy"'
        description: |
          A JSON string describing the platform tags to run the workflow on.
      project:
        type: string
        required: true
        description: |
          The name of the project in TIOBE web
      # tics-auth-token:
      #   type: string

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ${{ fromJson(inputs.platform-tags) }}
    env:
      UV_FROZEN: "true"
      UV_PYTHON_PREFERENCE: only-system
      UV_PYTHON_DOWNLOADS: never
      UV_PROJECT_ENVIRONMENT: /tmp/tics_env
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up uv with caching
        id: setup-uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-suffix: ${{ toJSON(matrix.platform) }}

      - name: Install dependencies
        run: |
          make setup-tests

      - name: Run tests
        run: |
          make test-coverage

      - name: Add XML coverage reports
        run: |
          uvx coverage xml
          mkdir results
          mv -t results .coverage coverage.xml htmlcov

      - name: Upload test coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-tics
          overwrite: true
          path: |
            results/

      - name: Install additional TiCS dependencies
        run: |
          source ${UV_PROJECT_ENVIRONMENT}/bin/activate
          echo "PATH=$PATH" >> $GITHUB_ENV
          uv pip install pylint pyflakes flake8

      - name: Run TiCS analysis
        uses: tiobe/tics-github-action@v3
        with:
          mode: qserver
          project: ${{ inputs.project }}
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
          branchdir: ${{ github.workspace }}
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          installTics: true
