name: Lint Python
on:
  workflow_call:
    inputs:
      source-files:
        description: "Whether the changes affect source files"
        type: string
        default: "true"
  # Because we have a uv.lock file, we can also use this workflow to lint ourselves.
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  files:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.3
        id: filter
        with:
          # Combine multiple negation checks into a union (¬A ∧ ¬B ∧ ¬C), because individual entries are checked independently (A ∨ B ∨ C).
          # If we ever need to filter only for docs, glob 'docs/**/*' and '**/*.md'
          filters: |
            source-files:
              - '!({docs/**,*.md,**/*.md,.readthedocs.yaml})'
      - name: Begin snap installs of common linters
        id: snap-install
        run: |
          echo -n "jobs=$(sudo snap install --no-wait codespell ruff shellcheck)" >> $GITHUB_OUTPUT
      - name: Set up uv with caching
        id: setup-uv
        uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
        with:
          enable-cache: true
      - name: Set up linters
        env:
          SNAP_JOBS: ${{ steps.snap-install.outputs.jobs }}
        run: |
          for job in ${SNAP_JOBS}; do
            sudo snap watch $job
          done

          # Try setting up the linters, but if it breaks try again after an apt update.
          # It's written this way because mostly we don't need apt-get update and it just
          # makes the job take longer, but when we do need it it's because a package deb
          # got removed that makes the linter setup fail. This gets fixed automatically
          # when GitHub rebuilds the image.
          if ! make -j setup-lint; then
            sudo apt-get update
            make -j setup-lint
          fi
      - name: Run all linters
        if: ${{ inputs.source-files == 'true' }}
        run: make -k lint
      - name: Run documentation linters
        if: ${{ inputs.source-files == 'false' }}
        run: make -k docs-lint
