# https://github.com/snapcrafters/ci/blob/main/.github/workflows/lint.yaml
name: Lint

on:
  pull_request:
  push:
    branches:
      - "main"
      - "feature/*"
      - "hotfix/*"
      - "release/*"
      - "renovate/*"
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up system for linting.
        run: |
          make setup-lint

      - name: Run linters
        run: |
          make -k lint

      - name: Run formatters
        run: |
          make -k format

      - name: Check for modifications to generated files
        run: |
          if [[ -n "$(git status -s)" ]]; then
            echo "Run 'make format' then commit/push changes"
            echo
            git diff
            exit 1
          fi
