name: Lint Python
on:
  workflow_call:
    inputs:
      source-files:
        description: "Whether the changes affect source files"
        type: string
        default: "true"
  # We also lint ourselves because we have a uv.lock file.
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  files:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Paths filter
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d
        id: filter
        with:
          # Combine negation checks into a union (¬A ∧ ¬B ∧ ¬C).
          # Entries are checked independently (A ∨ B ∨ C), so we combine them.
          # If we filter docs only, use glob 'docs/**/*' and '**/*.md'
          filters: |
            source-files:
              - '!({docs/**,*.md,**/*.md,.readthedocs.yaml})'
      - name: Install retry
        run: sudo apt-get update && sudo apt-get install -y retry
      - name: Begin snap installs of common linters
        id: snap-install
        run: |
          echo -n "jobs=$(retry sudo snap install --no-wait \
            codespell ruff shellcheck)" >> $GITHUB_OUTPUT
      - name: Set up uv with caching
        id: setup-uv
        uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4
        with:
          enable-cache: true
      - name: Set up linters
        env:
          SNAP_JOBS: "${{ steps.snap-install.outputs.jobs }}"
        run: |
          for job in ${SNAP_JOBS}; do
            sudo snap watch "$job"
          done

          # Set up linters. If it breaks, retry after apt-get update.
          # We avoid the update mostly since it adds time, but it fixes failures
          # when a deb gets removed (fixed by GitHub image rebuilds).
          if ! make -j setup-lint; then
            sudo apt-get update
            make -j setup-lint
          fi
      - name: Run all linters
        if: ${{ inputs.source-files == 'true' }}
        run: make -k lint
      - name: Run documentation linters
        if: ${{ inputs.source-files == 'false' }}
        run: make -k docs-lint