name: Check what the renovate run would do.
on:
  pull_request:
    paths:
      - ".github/workflows/self-test-renovate.yaml"
      - "renovate.json5"
  push:
    branches:
      - work/renovate # For development
  # Allows triggering the workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      enable_ssh_access:
        type: boolean
        description: "Enable ssh access"
        required: false
        default: false
  # Allow this workflow to be called
  workflow_call:
jobs:
  renovate:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
      - name: Set up uv with caching
        id: setup-uv
        uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
        with:
          enable-cache: true
          cache-suffix: ${{ steps.runner-info.outputs.cache-hash }}
      - name: Install renovate
        run: npm install --global re2 renovate
      - name: Enable ssh access
        uses: mxschmitt/action-tmate@35b54afac29c97fb54faba5b513f8fbd1882f113 # v3.24
        if: ${{ inputs.enable_ssh_access }}
        with:
          limit-access-to-actor: true
      - name: Check renovate config
        run: renovate-config-validator renovate.json5
      - name: Renovate dry-run
        run: |
          renovate --platform=local --dry-run=full
        env:
          RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RENOVATE_USE_BASE_BRANCH_CONFIG: ${{ github.ref }}
          LOG_LEVEL: debug
