name: QA self-test
on:
  pull_request:

jobs:
  lint-python:
    uses: ./.github/workflows/lint-python.yaml
  test-python:
    uses: ./.github/workflows/test-python.yaml
  test-python-custom:
    uses: ./.github/workflows/test-python.yaml
    with:
      fast-platforms: '["ubuntu-latest"]'
      fast-python-versions: '["3.14"]'
      slow-platforms: '["ubuntu-latest"]'
      slow-python-versions: '["3.14"]'
      lowest-python-version: '["3.0"]'
