name: QA self-test
on:
  pull_request:

jobs:
  lint-python:
    uses: ./.github/workflows/lint-python.yaml
  test-python:
    uses: ./.github/workflows/test-python.yaml
    secrets:
      secret-1: ${{ secrets.REPO_SECRET }}
    with:
      extra-env-vars: |
        REPO_VARIABLE=${{ vars.REPO_VARIABLE }}
        REPO_SECRET=$SECRET_1
  test-python-custom:
    uses: ./.github/workflows/test-python.yaml
    secrets:
      secret-1: ${{ secrets.REPO_SECRET }}
    with:
      # Test on many OS's to ensure that these workflows work everywhere.
      # Also ensure we can add a list of tags for self-hosted runners.
      fast-test-platforms: '[["jammy", "amd64"], ["noble", "arm64"], "ubuntu-22.04", "windows-latest", "macos-latest"]'
      fast-test-python-versions: '["3.14"]'
      slow-test-platforms: '["ubuntu-latest"]'
      slow-test-python-versions: '["3.14"]'
      lowest-python-version: "3.8"
      lowest-python-platform: '["jammy", "arm64"]'
      use-lxd: true
      pytest-markers: smoketest and not steamtest
      setup-vars: SETUP_EXTRA=1
      extra-env-vars: |
        REPO_VARIABLE=${{ vars.REPO_VARIABLE }}
        REPO_SECRET=$SECRET_1
  test-python-as-root:
    uses: ./.github/workflows/test-python.yaml
    secrets:
      secret-1: ${{ secrets.REPO_SECRET }}
    with:
      # Test on many OS's to ensure that these workflows work everywhere.
      # Also ensure we can add a list of tags for self-hosted runners.
      fast-test-platforms: '["ubuntu-latest"]'
      fast-test-python-versions: '["3.14"]'
      slow-test-platforms: '["ubuntu-latest"]'
      slow-test-python-versions: '["3.14"]'
      lowest-python-version: "3.8"
      lowest-python-platform: "ubuntu-latest"
      test-command-prefix: sudo -E # Test that we can run with sudo.
      extra-env-vars: |
        REPO_VARIABLE=${{ vars.REPO_VARIABLE }}
        REPO_SECRET=$SECRET_1
  test-python-noop-platforms: # Test that the Python tests are all skipped when platforms are empty
    uses: ./.github/workflows/test-python.yaml
    with:
      fast-test-platforms: ""
      slow-test-platforms: ""
      lowest-python-platform: ""
  test-python-noop-versions: # Test that the Python tests are all skipped when versions are empty
    uses: ./.github/workflows/test-python.yaml
    with:
      fast-test-python-versions: ""
      slow-test-python-versions: ""
      lowest-python-version: ""
