name: Test tools
on:
  workflow_call:
  pull_request:

jobs:
  contributors:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          # minimum supported version for the contributors script
          python-version: 3.11
      - name: Run contributor script
        run: |
          ./tools/contributors.py --project rockcraft --old-ref 1.16.0 --new-ref bd7109b --verbose
