name: TICS

on:
  workflow_call:
    inputs:
      project:
        type: string
        required: true
        description: |
          Tiobe Tics project to publish results for
    secrets:
      TICSAUTHTOKEN:
        required: true

jobs:
  TICS:
    permissions:
      contents: read
    runs-on: [self-hosted, amd64, tiobe, noble]
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup project
        run: make setup-tics

      - name: Run coverage
        run: make test-coverage

      - name: Upload test results
        if: success() || failure()
        uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7.0.2
        with:
          name: test-results-${{ inputs.project }}
          path: results/

      - name: Run TICS analysis
        uses: tiobe/tics-github-action@06afa6781ba53ab58efbe766d41d84febad1f683 # v4.0.0
        with:
          mode: qserver
          project: ${{ inputs.project }}
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
          branchdir: ${{ github.workspace }}
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          installTics: true
